module.exports = {
    "page_read": [
        {
            "ID": "Dashboard_1",
            "PAGEID": "Dashboard_1",
            "PAGENAME": "Dashboard_1",
            "CREATED_BY": "fundsonline",
            "CREATED_ON": "01-04-2025",
            "LASTUPDATED_BY": "fundsonline",
            "LASTUPDATED_ON": "08-04-2025",
            "PAGESPATH": "pages"
        },
        {
            "ID": "Dashboard_2",
            "PAGEID": "Dashboard_2",
            "PAGENAME": "Dashboard_2",
            "CREATED_BY": "aditya",
            "CREATED_ON": "25-11-2024",
            "LASTUPDATED_BY": "suraj",
            "LASTUPDATED_ON": "12-03-2025",
            "PAGESPATH": "pages"
        }
    ],
    "page_process_filter": [],
    "page_process_r": ["VGVzdCBEYXRhIA=="],
    "page_process":["ICAgPG1haW4gY2xhc3M9ImNvbCBwLTIiPg0KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImQtZmxleCBqdXN0aWZ5LWNvbnRlbnQtYmV0d2VlbiBmbGV4LXdyYXAgZmxleC1tZC1ub3dyYXAgYWxpZ24taXRlbXMtY2VudGVyIG1iLTMgYm9yZGVyLWJvdHRvbSI+DQogICAgICAgICAgICAgICAgICAgIDxoMSBjbGFzcz0iaDIiPkRhc2hib2FyZDwvaDE+DQogICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImJ0bi10b29sYmFyIj4NCiAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iYnRuLWdyb3VwIj4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxidXR0b24gdHlwZT0iYnV0dG9uIiBjbGFzcz0iYnRuIGJ0bi1zbSBidG4tb3V0bGluZS1zZWNvbmRhcnkiPlNoYXJlPC9idXR0b24+DQogICAgICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIHR5cGU9ImJ1dHRvbiIgY2xhc3M9ImJ0biBidG4tc20gYnRuLW91dGxpbmUtc2Vjb25kYXJ5Ij5FeHBvcnQ8L2J1dHRvbj4NCiAgICAgICAgICAgICAgICAgICAgPC9kaXY+DQogICAgICAgICAgICAgICAgICAgIDwvZGl2Pg0KICAgICAgICAgICAgICAgIDwvZGl2Pg0KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9InJvdyBtYi0zIj4NCiAgICAgICAgICAgICAgICAgICAgPGRpdiAgY2xhc3M9ImNvbC0xMiBjb2wtbGctNiI+DQogICAgICAgICAgICAgICAgICAgICAgICA8YmFyLWNoYXJ0IDpkYXRhPSJbNDAsIDM5LCAxMCwgNDAsIDM5LCA4MCwgNDBdIiAgbGFiZWw9IkJhciBDaGFydCIgOmxhYmVscz0iWydKYW51YXJ5JywgJ0ZlYnJ1YXJ5JywgJ01hcmNoJywgJ0FwcmlsJywgJ01heScsICdKdW5lJywgJ0p1bHknXSIvPg0KICAgICAgICAgICAgICAgICAgICA8L2Rpdj4NCiAgICAgICAgICAgICAgICAgICAgPGRpdiAgY2xhc3M9ImNvbC0xMiBjb2wtbGctNiI+DQogICAgICAgICAgICAgICAgICAgICAgICA8bGluZS1jaGFydCA6ZGF0YT0iWzQwLCAzOSwgMTAsIDQwLCAzOSwgODAsIDQwXSIgIGxhYmVsPSJMaW5lIENoYXJ0IiA6bGFiZWxzPSJbJ0phbnVhcnknLCAnRmVicnVhcnknLCAnTWFyY2gnLCAnQXByaWwnLCAnTWF5JywgJ0p1bmUnLCAnSnVseSddIi8+DQogICAgICAgICAgICAgICAgICAgIDwvZGl2Pg0KICAgICAgICAgICAgICAgIDwvZGl2Pg0KDQogICAgICAgICAgICAgICAgPGgyPlNlY3Rpb24gdGl0bGU8L2gyPg0KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9InRhYmxlLXJlc3BvbnNpdmUiPg0KICAgICAgICAgICAgICAgICAgICA8dGFibGUgY2xhc3M9InRhYmxlIHRhYmxlLXN0cmlwZWQgdGFibGUtc20iPg0KICAgICAgICAgICAgICAgICAgICA8dGhlYWQ+DQogICAgICAgICAgICAgICAgICAgICAgICA8dHI+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRoPiM8L3RoPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0aD5IZWFkZXI8L3RoPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0aD5IZWFkZXI8L3RoPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0aD5IZWFkZXI8L3RoPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0aD5IZWFkZXI8L3RoPg0KICAgICAgICAgICAgICAgICAgICAgICAgPC90cj4NCiAgICAgICAgICAgICAgICAgICAgPC90aGVhZD4NCiAgICAgICAgICAgICAgICAgICAgPHRib2R5Pg0KICAgICAgICAgICAgICAgICAgICAgICAgPHRyPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZD4xLDAwMTwvdGQ+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRkPnJhbmRvbTwvdGQ+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRkPmRhdGE8L3RkPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZD5wbGFjZWhvbGRlcjwvdGQ+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRkPnRleHQ8L3RkPg0KICAgICAgICAgICAgICAgICAgICAgICAgPC90cj4NCiAgICAgICAgICAgICAgICAgICAgICAgIDx0cj4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGQ+MSwwMDI8L3RkPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZD5wbGFjZWhvbGRlcjwvdGQ+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRkPmlycmVsZXZhbnQ8L3RkPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZD52aXN1YWw8L3RkPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZD5sYXlvdXQ8L3RkPg0KICAgICAgICAgICAgICAgICAgICAgICAgPC90cj4NCiAgICAgICAgICAgICAgICAgICAgPC90Ym9keT4NCiAgICAgICAgICAgICAgICAgICAgPC90YWJsZT4NCiAgICAgICAgICAgICAgICA8L2Rpdj4NCiAgICAgICAgICAgIDwvbWFpbj4="]
}